services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: xflair/prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - SERVICE_HOST=host.docker.internal
    env_file:
      - .env.local
    depends_on:
      - model

  model:
    build:
      context: ./Models/TensorFlow
      dockerfile: Dockerfile
    image: xflair/tensorflow:latest
    ports:
      - "5001:5000"
    env_file:
      - .env.local
    entrypoint: /TensorFlow/start/start.sh