services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: xflair/dev:latest
    ports:
      - '3000:3000'
    environment:
      - mode=development
      - SERVICE_HOST=host.docker.internal
      - FLASK_ENV=development
    env_file:
      - .env.local
    depends_on:
      - model
    volumes:
      - ./:/usr/src/xflair

  model:
    build:
      context: ./Models/TensorFlow
      dockerfile: Dockerfile
    image: xflair/tensorflow:latest
    ports:
      - '5001:5000'
    env_file:
      - .env.local
    entrypoint: /TensorFlow/start/start.sh
    volumes:
      - ./Models/TensorFlow:/TensorFlow
    environment:
      - FLASK_APP=server.py
      - FLASK_DEBUG=1
